[package]
name = "rustbox"
version = "0.2.0"
authors = ["Greg Chapple <gregchapple1@gmail.com>"]
description = "A rust implementation of the termbox library"
repository = "https://github.com/gchp/rustbox"
homepage = "https://github.com/gchp/rustbox"
readme = "README.md"
license = "MIT"
keywords = [
    "termbox",
    "terminal",
    "gui",
]
exclude = [
    "examples/*"
]

[lib]
name = "rustbox"

[dependencies.termbox-sys]
git = "https://github.com/gchp/termbox-sys"
